In [2]:
# Code from Chapter 3 of Machine Learning: An Algorithmic Perspective (2nd Edition)
# by Stephen Marsland (http://stephenmonika.net)

# You are free to use, change, or redistribute the code in any way you wish for
# non-commercial purposes, but please maintain the name of the original author.
# This code comes with no warranty of any kind.

# Stephen Marsland, 2008, 2014

import numpy as np

In [44]:
class pcn:
    # A basic perceptron
    def __init__(self, inputs, targets):
        # Set up the network size
        self.nIn = np.shape(inputs)[1]
        self.nOut = np.shape(targets)[1]
        self.nData = np.shape(inputs)[0]
        
        self.weights = np.random.rand(self.nIn + 1, self.nOut)
        
    def pcnTrain(self, inputs, targets, alpha, nIter):
        # Add bias node
        inputs = np.concatenate((inputs, np.ones((np.shape(inputs)[0],1))),axis=1)
        
        # Train
        for n in range(nIter):
            self.activations = self.pcnForward(inputs)
            print(self.weights)
            print(self.activations)
            self.weights += alpha * np.dot(np.transpose(inputs),targets - self.activations)            

    
    def pcnForward(self, inputs):
        activations = np.dot(inputs, self.weights)
        return np.where(activations > 0 , 1, 0)
        

In [45]:
dataOr = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,1]])

trainX = dataOr[:,0:2]
trainY = dataOr[:,2:]
p = pcn(trainX, trainY)
p.pcnTrain(trainX,trainY,0.25,5)

[[0.54691564]
 [0.09952408]
 [0.21167721]]
[[1]
 [1]
 [1]
 [1]]
[[ 0.54691564]
 [ 0.09952408]
 [-0.03832279]]
[[0]
 [1]
 [1]
 [1]]
[[ 0.54691564]
 [ 0.09952408]
 [-0.03832279]]
[[0]
 [1]
 [1]
 [1]]
[[ 0.54691564]
 [ 0.09952408]
 [-0.03832279]]
[[0]
 [1]
 [1]
 [1]]
[[ 0.54691564]
 [ 0.09952408]
 [-0.03832279]]
[[0]
 [1]
 [1]
 [1]]
